[end_point]
url = https://ioe-api.nextdrive.io

[params]
email = automan+api@nextdrive.io
password = link4581
clientid = b5irdgn42h50t1jg3thcdm0ci
accesstoken = eyJhbGciOiJSUzI1NiIsInR5cGUiOiJKV1QifQ.eyJpYXQiOjE2OTgxMTM3NzAsImlzcyI6Im5leHRkcml2ZS5pbyIsImF1ZCI6Im5leHREcml2ZS9hY2Nlc3NUb2tlbiIsImp0aSI6IjIxODk4YjhhLTlhZjktNGIwZi04MjA1LWZjZjNiYzRjNDg2ZiIsImV4cCI6MTY5ODE0MjU3MSwic3ViIjoiNTAyYmVmYWUtYjA0ZC00YmQwLWEwZjUtMWFmNDNlN2RmZGExIiwiYXBwVXVpZCI6bnVsbCwicGFja2FnZU5hbWUiOiJpby5uZXh0ZHJpdmUuZWNvZ2VuaWUiLCJjbGllbnRJZCI6ImI1aXJkZ240Mmg1MHQxamczdGhjZG0wY2kiLCJwb29sSWQiOiJhcC1ub3J0aGVhc3QtMV9kaFRHQ0wxYngiLCJ1c2VyUm9sZXMiOlsiRW5kVXNlciJdfQ.C6ybuH0P2xRmB1G0yWjymZbda_UMyV9jPDQxa8jm6y6HzRNTfFVCi5OBWOkIopH3JAu7offBET_WClVrzp4OWekM49Lk7VcgTtM-A5mIh5-dTT-JS2xpptp0SwTYxTghw1GexQiRVYdX1KL4fVV53sL6mobziW6dbsc-3C6B-nUFiBd6SgekmFq_FxfFgchj-XrqTUnqun-9u-Y--fesr6ta-fJ1zFne8KKaJteyrsZcnC_qArBB63bbI-twduVc4cJi4GMaqky-qex36tRvoJm2JiH8MESb7e4WTzzdIjenTQBoWFtZQOet6BtK1p13TG06DwRwPjjsA5-fpaKYdQ
gw_pid = JAB3410D07A5E45D0
gw_hardwareid = 10d07a5e-45d0-011a-2830-0006d0789d22
gw_name = CubeJ-5e45d0
ble_protocol = ble
gw_dsn = ND8FOX0045551
ble_name = Motion
ble_model = Pixi-G
ble_macaddress = 98:07:2d:ad:42:8c
ble_dsn = VGBI2N0077294
online_gw_dsn = ND8FOX0066636
page = 1
user_uuid = 502befae-b04d-4bd0-a0f5-1af43e7dfda1

