[end_point]
url = https://eg-api-node.nextdrive.io
ums_url = https://ioe-api.nextdrive.io

[params]
email = automan+api@nextdrive.io
password = link4581
clientid = b5irdgn42h50t1jg3thcdm0ci
appuuid = 0c7fd556-0c3e-4793-b7bb-15bfb1604b81
accesstoken = eyJhbGciOiJSUzI1NiIsInR5cGUiOiJKV1QifQ.eyJpYXQiOjE3ODE2MDIzOTUsImlzcyI6Im5leHRkcml2ZS5pbyIsImF1ZCI6Im5leHREcml2ZS9hY2Nlc3NUb2tlbiIsImp0aSI6ImM2NzVkZjMyLTIwMDAtNGQ4Mi1hZGE4LTk2ZmYzYzgyNjAyZCIsImV4cCI6MTc4MTYzMTE5Niwic3ViIjoiNTAyYmVmYWUtYjA0ZC00YmQwLWEwZjUtMWFmNDNlN2RmZGExIiwiYXBwVXVpZCI6IjBjN2ZkNTU2LTBjM2UtNDc5My1iN2JiLTE1YmZiMTYwNGI4MSIsInBhY2thZ2VOYW1lIjoiaW8ubmV4dGRyaXZlLmVjb2dlbmllIiwiY2xpZW50SWQiOiJiNWlyZGduNDJoNTB0MWpnM3RoY2RtMGNpIiwicG9vbElkIjoiYXAtbm9ydGhlYXN0LTFfZGhUR0NMMWJ4IiwidXNlclJvbGVzIjpbIkVuZFVzZXIiXX0.Gx9vg9ckdiVnqWppJIzLRJQPik0pUhltZmE7iK_jF15WR3B2_Zn_iSE715-CfALOVerE4733b_JH-UW8Oi5QrVGXzp7zzf1FNZwvfFeGwplpylkYEaIcVnaa6_VMgjpYJSQJNFq9xZOXU0f3JR2JiN5Yz4koxQud0vT3TzwyiMWUEabiLnUw3PcxZp8mUlThPlWqzMMVkCKOi97yJf_Nr6E97NLTv6wIUhBYjGk2OYKn9AogP10Gk4pyWByvfCXfB92c9xtRtok1Nj0C8cQgNhMPmY2Oq7QPHpT3AB5-MUAsveBVmHt6xINMMrrq0gJDotRPOR_7KX6nr811b_vQEQ
gw_pid = JAB3410D07A5E45D0
gw_hardwareid = 10d07a5e-45d0-011a-2830-0006d0789d22
gw_name = CubeJ-5e45d0
gw_uuid = f4ab7826-4d3d-46d4-a20a-9e8215baa5f9
ble_name = Motion
ble_model = Pixi-G
ble_macaddress = 98:07:2d:ad:42:8c
ble_service = ble
ble_uuid = 60cd0bb2-cd11-463a-99f7-e28de680f845
aircon_brandid = 1
postnextstarttime = 1686823200000
modbus_brandid = 1
ble_brandid = 1
online_gw_uuid = 565bb338-5c7e-4af4-a57f-fa271b2980a5
postalcode = 7000001
postkeyword = Cube

